location            = "westeurope"
resource_group_name = "my-project-rg"
project_name        = "my-project"
alert_email         = "test@domain.com"
vm_name             = "my-linux-vm"
bastion_ip          = "192.168.1.1"
subscription_id     = "subscription_id_here"